tasks:
  - before: |
      pip install colorama
      mkdir -p ~/scripts
      echo '
      from colorama import init, Fore, Style

      def display_banner():
          init(autoreset=True)
          banner = r"""
           ____ _                 _                _____     _ _          
          / ___| | ___  _   _  __| |_ __ ___  _   |_   _| __(_) |__   ___ 
         | |   | |/ _ \| | | |/ _` | '' '_ ` '' _ \| | | || || ''__| | ''_ \ / _ \
         | |___| | (_) | |_| | (_| | | | | | | |_| || || |  | | |_) |  __/
          \____|_|\___/ \__,_|\__,_|\__,_|_| |_| |_|\__, ||_||_|  |_|_.__/ \___|
                                            |___/                        
          Welcome to CloudmyTribe!
          """
          print(Fore.MAGENTA + banner)

      if __name__ == "__main__":
          display_banner()
      ' > ~/scripts/cloudmytribe_banner.py
      chmod +x ~/scripts/cloudmytribe_banner.py
      echo '
      # Display CloudmyTribe banner on terminal start and clear screen
      python3 ~/scripts/cloudmytribe_banner.py

      # Alias clear command to keep the banner visible
      alias clear="clear && python3 ~/scripts/cloudmytribe_banner.py"
      ' >> ~/.bashrc
      echo '
      # Display CloudmyTribe banner on terminal start and clear screen
      python3 ~/scripts/cloudmytribe_banner.py

      # Alias clear command to keep the banner visible
      alias clear="clear && python3 ~/scripts/cloudmytribe_banner.py"
      ' >> ~/.zshrc
  init: source ~/.bashrc || source ~/.zshrc
